
###
//Create a new fo
POST http://localhost:3000/product/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwLCJpYXQiOjE3MTIyMTI2NzIsImV4cCI6MTcxMjIxNDQ3Mn0.TKUbp2xXuT0E26_UVf1G5PUWmmKovFQB44uSOUmvsNk
Content-Type: application/json

{
    "productCode" : "OG_PR_25"
}

###

###
POST  {{baseUrl}}/product/remove
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwODMyMjM2NSwiZXhwIjoxNzA4MzIyOTY1fQ.Q87XBYsMPvhCpyX03Oz1NQsbgkUnleFXh4oEMrY6tl4

###
###
POST  http://localhost:3000/product/list-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwOTI5MjcwOCwiZXhwIjoxNzA5MjkzOTA4fQ.QgJlzinrMx1mkvrYNzS0uyUcpYq8f0NfLmIqeJhuv94

###
###
POST  http://localhost:3000/product/start-job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwLCJpYXQiOjE3MTIyMTQ5NjksImV4cCI6MTcxMjIxNjc2OX0.-ku4eena3yfNnwv2yiYR1PxXAZ0kHwnG9MA7o4c7dxI
###
POST  http://localhost:3000/product/check-job-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3MDk3MTAxMTQsImV4cCI6MTcwOTcxMTMxNH0.ijhiw4mSG_grDlNNLtdr6GkqWhxZZfn03tNdcnm9aIg
Content-Type: application/json

{
    "jobId": "01HR995GYSEEB8FSGR0WW6TNS9",
    "requestId":"01HR995GX86716W23YWD0T6RK8"
}

###
###
POST  http://localhost:3000/product/recent-readings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3MTAzMDk0NTYsImV4cCI6MTcxMDMxMDY1Nn0.lnsKVk88raHWYieeAJZx-h-JvwdARE67QB4FbvlDKFI
###