
###
//Create a new folder
POST http://localhost:3000/product/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwODk0MTU1MiwiZXhwIjoxNzA4OTQyMTUyfQ.5f2rvhIf_aOG7ZsEnEWlG4chuFlJHS-wVMKgMfLHQC0
Content-Type: application/json

{
    "productCode" : "OG_PR_01"
}
###

###
POST  http://localhost:3000/product/remove
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwODMyMjM2NSwiZXhwIjoxNzA4MzIyOTY1fQ.Q87XBYsMPvhCpyX03Oz1NQsbgkUnleFXh4oEMrY6tl4

###

###
POST  http://localhost:3000/product/start-job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwOTAxNTI4NCwiZXhwIjoxNzA5MDE2NDg0fQ.S7lxp5RefyrhoDxqMb62StLwTGawzmQ0pF01vG3RNwU