
###
//Create a new folder
POST http://localhost:3000/product/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwOTI5MjcwOCwiZXhwIjoxNzA5MjkzOTA4fQ.QgJlzinrMx1mkvrYNzS0uyUcpYq8f0NfLmIqeJhuv94
Content-Type: application/json

{
    "productCode" : "OG_PR_01"
}
###

###
POST  {{baseUrl}}/product/remove
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwODMyMjM2NSwiZXhwIjoxNzA4MzIyOTY1fQ.Q87XBYsMPvhCpyX03Oz1NQsbgkUnleFXh4oEMrY6tl4

###
###
POST  http://localhost:3000/product/list-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwOTI5MjcwOCwiZXhwIjoxNzA5MjkzOTA4fQ.QgJlzinrMx1mkvrYNzS0uyUcpYq8f0NfLmIqeJhuv94

###
###
POST  http://localhost:3000/product/start-job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3MDk3MjU3MzgsImV4cCI6MTcwOTcyNjkzOH0.5ZCaf_rs85lld7tUcHNTdRoze7pykCQ9RvzizxEkk-8
###
POST  http://localhost:3000/product/check-job-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3MDk3MTAxMTQsImV4cCI6MTcwOTcxMTMxNH0.ijhiw4mSG_grDlNNLtdr6GkqWhxZZfn03tNdcnm9aIg
Content-Type: application/json

{
    "jobId": "01HR995GYSEEB8FSGR0WW6TNS9",
    "requestId":"01HR995GX86716W23YWD0T6RK8"
}

###
###
POST  http://localhost:3000/product/recent-readings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE3MDk4ODMzNDMsImV4cCI6MTcwOTg4NDU0M30.-Qz9Pz_i4Vcz-xNBVD7ZhNIuFL9zkm_E8qUzExT7_PE
###