###

POST http://localhost:3500/client/read-data
Content-Type: application/json

{
    "userId" : 2,
    "productCode" : "OG_PR_01",
    "requestId" : "0001"
}

###

###

POST http://localhost:3500/client/status
Content-Type: application/json

{
    "job_id": "01HQ85T77K3VKPD66VK559RR7P"
}


###

###

POST http://localhost:5000/client/register-client
Content-Type: application/json

{
    "userId": 20,
    "productCode" : "OG_PR_25",
    "url" : "192.168.1.1:3000"
}


###