###

POST http://localhost:3500/client/read-data
Content-Type: application/json

{
    "user_id" : 2,
    "product_code" : "OG_PR_01",
    "request_id" : ""
}

###

###

POST http://localhost:3500/client/status
Content-Type: application/json

{
    "job_id": "01HQ38CBAMJKWGTHFKN36Q6E2N"
}


###