const READ_DATA_CONSTANTS = {
  CAPTURE_DELAY: 8000,
  TOTAL_DURATION: 128000,
  PORT: 3500,
};

const RECENT_DATA_CONSTANTS = {
  SUCCESS: "ok",
  FAILED: "Empty",
};

const RESPONSE_STATUS_CONSTANTS = {
  SUCCESS: 200 || 201,
  FAILED: 400 || 401,
  SERVER_ERROR: 500,
};
const ARRAY_CONSTANTS = {
  LENGTH_ZERO: 0,
};
const DUMMYDATA_CONSTANTS = {
  DATA: "DUMMY DATA",
};
module.exports = {
  READ_DATA_CONSTANTS,
  RECENT_DATA_CONSTANTS,
  RESPONSE_STATUS_CONSTANTS,
  ARRAY_CONSTANTS,
  DUMMYDATA_CONSTANTS,
};
